const SAFE_ASSET_RESOLUTION_CODES = new Set([
  'ORACLE_UNAVAILABLE', 'ASSET_PROVIDER_UNAVAILABLE', 'INVALID_ASSET_PROVIDER_RESPONSE',
  'CORE_PROGRAM_OWNER_MISMATCH', 'CORE_COLLECTION_OWNER_MISMATCH', 'CORE_CUSTODY_MISMATCH',
  'CORE_OWNER_CHANGED', 'CORE_COLLECTION_MISMATCH',
  'UNSUPPORTED_COMPRESSED_ASSET', 'CNFT_IDENTITY_MISMATCH', 'CNFT_ASSET_ID_MISMATCH',
  'CNFT_TREE_OWNER_MISMATCH', 'CNFT_PROOF_INCOMPLETE', 'CNFT_PROOF_SIZE_UNSUPPORTED',
  'CNFT_STALE_PROOF_REFETCH_REQUIRED', 'CNFT_CUSTODY_MISMATCH', 'CNFT_OWNER_CHANGED',
  'ONLY_SINGLE_UNIT_COLLECTIBLES_SUPPORTED', 'TOKEN_2022_EXTENSIONS_UNSUPPORTED',
  'TOKEN_ACCOUNT_EXTENSION_UNSUPPORTED', 'TOKEN_CUSTODY_REMAINS', 'METADATA_OWNER_MISMATCH', 'METADATA_MINT_MISMATCH',
  'MINT_MISSING', 'UNSUPPORTED_COLLECTIBLE_SHAPE', 'TOKEN_CUSTODY_MISMATCH',
  'PNFT_ACCOUNTS_MISSING', 'PNFT_METADATA_MISMATCH', 'PNFT_RULE_SET_NOT_CLAIMABLE',
  'WRONG_ASSET_OWNER', 'COLLECTIBLE_TOKEN_ACCOUNT_MISSING',
  'COLLECTIBLE_NOT_SUPPORTED', 'CLAIMABILITY_EVIDENCE_REQUIRED', 'CLAIMABILITY_IDENTITY_MISMATCH',
  'SPL_CURRENT_TRANSFER_FROZEN', 'TOKEN_2022_CURRENT_TRANSFER_FROZEN', 'CORE_CURRENT_TRANSFER_BLOCKED',
  'SPL_MUTABLE_TRANSFER_AUTHORITY_UNSUPPORTED', 'TOKEN_2022_FREEZE_AUTHORITY_UNSUPPORTED',
  'TOKEN_2022_CUSTODY_DELEGATE_UNSUPPORTED', 'PNFT_MUTABLE_METADATA_UNSUPPORTED',
  'PNFT_RULE_SET_UNSUPPORTED', 'PNFT_EXTERNAL_DELEGATE_UNSUPPORTED',
  'PNFT_LOCKED_TOKEN_RECORD_UNSUPPORTED', 'CORE_EXTERNAL_FREEZE_AUTHORITY_UNSUPPORTED',
  'CORE_BLOCKING_PLUGIN_UNSUPPORTED', 'CORE_NONTRANSFERABLE_UNSUPPORTED',
  'CORE_MUTABLE_TRANSFER_CONTROL_UNSUPPORTED', 'CNFT_PROOF_REFRESH_REQUIRED',
  'CNFT_EXTERNAL_LEAF_DELEGATE_UNSUPPORTED', 'SOL_COMMIT_TRANSFER_UNSUPPORTED',
])

export function safeAssetResolutionErrorCode(code: string | undefined): string {
  if (!code) return 'UNKNOWN'
  if (SAFE_ASSET_RESOLUTION_CODES.has(code)) return code
  const positional = /^([A-Z0-9_]+):(maker|taker):\d+$/.exec(code)
  return positional && SAFE_ASSET_RESOLUTION_CODES.has(positional[1]) ? positional[1] : 'UNKNOWN'
}


const TRANSIENT_ASSET_CODES = new Set([
  'ORACLE_UNAVAILABLE', 'ASSET_PROVIDER_UNAVAILABLE',
  'INVALID_ASSET_PROVIDER_RESPONSE', 'CNFT_STALE_PROOF_REFETCH_REQUIRED',
])

/** Bounded service-boundary contract: never return upstream free-form text. */
export function sessionOracleFailure(path: string, rawCode: unknown): { status: number; code: string } {
  if (path === '/trade-authority/session/read' && rawCode === 'SESSION_NOT_YET_OBSERVED') {
    return { status: 503, code: 'SESSION_NOT_YET_OBSERVED' }
  }
  const code = safeAssetResolutionErrorCode(typeof rawCode === 'string' ? rawCode : undefined)
  if (TRANSIENT_ASSET_CODES.has(code)) return { status: 503, code }
  if (path === '/trade-authority/assets' && code !== 'UNKNOWN') return { status: 422, code }
  return { status: 503, code: 'ORACLE_UNAVAILABLE' }
}
